
[cursor]
blink_interval = 500
unfocused_hollow = false
thickness = 0.2

[cursor.style]
blinking = "On"
# shape = 'Beam'
shape = 'Block'

[font]
size = 11.0

[font.italic]
# family = "Hasklug Nerd Font Mono"
family = "Firacode Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
# family = "FiraCode Nerd Font"
family = "Firacode Nerd Font"
style = "Regular"

[font.bold]
# family = "FiraCode Nerd Font"

family = "Firacode Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = true

# [shell]
# program = "/bin/zsh"

[window]
# decorations = "Buttonless"
opacity = 1
# values for opacity from 0.1 to 1.0
# startup_mode = "Fullscreen"

[window.padding]
x = 5
y = 5

[general]
# import = ["~/.config/alacritty/themes/themes/snazzy.toml"]
# import = ["~/.config/alacritty/themes/themes/monokai.toml"]


live_config_reload = true


# import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]
# import = ["~/.config/alacritty/themes/themes/nightfox.toml"]

import = ["~/.config/alacritty/themes/themes/CUSTOM_nightfox.toml"]
# import = ["~/.config/alacritty/themes/tokyo-night.toml"]
